# Defore install it to ESP32, verify if all names are OK. 

substitutions:
  device_name: "aquaeye"
  friendly_name: "AquaEye"
  #dns: "aquaeye.casa"


# PINs as the project on EASYEDA
  dist_pin_eco: "GPIO4"
  dist_pin_trig: "GPIO3"
  temp_pin: "GPIO1"
  scl_pin: "GPIO9"
  sda_pin: "GPIO8"
  flux_pin: "GPIO10"
  falha_pin: "GPIO0"            # Fail PIN
  alerta_pin: "GPIO20"          # Alert light
  ph_pin: "GPIO2"

  nivel_time: "20s"
  temp_time: "60s"
  flux_time: "60"
  ph_time: "60s"
  luz_tempo: "60s"

packages: 
  device_base: !include device_base.yaml    # Device Base contains general configurations common to all my devices
  wifi: !include wifi.yaml                  # WIFI configuration

######################################################################
esp32:
  board: esp32-c3-devkitm-1
  variant: ESP32C3
  framework:
    type: esp-idf

external_components:
  - source: github://pr#7942
    refresh: 30s
    components:
      - adc
######################################################################
wifi:
  output_power: 8.5dB

  # Example configuration entry
logger:
  level: DEBUG
####################################################################
globals:
  - id: retorno
    type: float
    initial_value: "0.0"
  - id: freq_fluxo                 # pulses per second per litre/minute of flow
    type: float
    restore_value: yes
    initial_value: "5"
  - id: sonic_offset                # Offset do Sensor até a água quando o tanque está cheio (em mm)
    type: int
    restore_value: yes
    initial_value: '23'
  - id: coluna_agua_total          # Medida da coluna de água quando o tanque está cheio (em mm)
    type: int
    restore_value: yes
    initial_value: '420'

####################################################################################
image:
  - file: "images/aquaeye-sologo.png"
    type: binary
    #transparency: alpha_channel
    id: logo
    resize: 20x20

font:
  - file: 'fonts/Audiowide.ttf'
    id: ftitulo
    size: 10

  - file: 'fonts/Roboto.ttf'
    id: finfo
    size: 10
    extras:
      - file: "fonts/materialdesignicons-webfont.ttf"
        glyphs: [
          "\U000F1A86",  # Temp
          "\U000F185B", # Nivel
          "\U000F185A",  # Fluxo
          ]    

  - file: 'fonts/HyperFatosRegular.otf'
    id:  bigdados
    size: 30
      
i2c:
  sda: ${sda_pin}
  scl: ${scl_pin}
  frequency: 400kHz

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    id: tela
    #update_interval: 5s
    pages:
      - id: pagina_temp
        lambda: |-
          it.printf(64, 0, id(ftitulo), TextAlign::TOP_CENTER, "Temperatura");
          it.printf(64, 32, id(bigdados), TextAlign::CENTER,  "%.1f C", id(temperatura).state);

      - id: pagina_nivel
        lambda: |-
          it.printf(64, 0, id(ftitulo), TextAlign::TOP_CENTER, "Nivel");
          it.printf(64, 32, id(bigdados), TextAlign::CENTER, "%.1f %%", id(nivel).state);
  

      - id: pagina_fluxo
        lambda: |-
          it.printf(64, 0, id(ftitulo), TextAlign::TOP_CENTER, "Fluxo");
          it.printf(64, 32, id(bigdados), TextAlign::CENTER, "%.1f L/h", id(fluxo_hora).state);

      - id: pagina_ph
        lambda: |-
          it.printf(64, 0, id(ftitulo), TextAlign::TOP_CENTER, "PH");
          it.printf(64, 32, id(bigdados), TextAlign::CENTER, "%.1f", id(ph_aquario).state);

      - id: pagina_lux
        lambda: |-
          it.printf(64, 0, id(ftitulo), TextAlign::TOP_CENTER, "LUX");
          it.printf(64, 32, id(bigdados), TextAlign::CENTER, "%.1f", id(lux_aquario).state);

interval:
  - interval: 5s
    then:
      - display.page.show_next: tela
      - component.update: tela

#=========================================================
# LED de ALERTA
# Defina o LED de alerta
light:
  - platform: binary
    internal: true
    name: "LED Alerta Sensores"
    id: led_alerta
    output: led_alerta_output

output:
  - platform: gpio
    pin: ${alerta_pin}
    id: led_alerta_output

binary_sensor:
  - platform: gpio
    pin:
      number: ${falha_pin}  # Altere para o pino que você usou
      mode: INPUT_PULLUP
      inverted: true  # O pino FLAG do TPS2553 se torna LOW em caso de falha.
    name: "Curto Circuito"
    entity_category: "diagnostic"
    # Adicione uma automação para quando o sensor detectar um curto
    on_press:
      - light.turn_on:
          id: led_alerta
          state: true
      - homeassistant.service:
          service: persistent_notification.create
          data:
            message: "Curto-circuito detectado nos sensores!"
            title: "Alerta de Curto-Circuito"
#=========================================================
# Example configuration entry
button:
  - platform: restart
    name: "Reiniciar"
    entity_category: diagnostic
    disabled_by_default: false
    
# SENSORES
####################################################################################
# TEMPERATURA
one_wire:
  - platform: gpio
    pin: ${temp_pin}

sensor:
  #------------------------------------------------------------#
  - platform: homeassistant
    id: ha_freq_fluxo
    entity_id: input_number.freq_fluxo_yuri
    on_value:
      then:
        if:
          condition:
              lambda: 'return id(freq_fluxo) != float(x);'
          then:
            - logger.log:
                level: INFO
                format: 'Mudança na Freq Fluxo : de %f para %f'
                args: ['id(freq_fluxo)', 'float(x)']
            - globals.set:
                id: freq_fluxo
                value: !lambda 'return float(x);'
  #------------------------------------------------------------#
  - platform: homeassistant
    id: ha_sonic_offset
    entity_id: input_number.sonic_offset_yuri
    on_value:
      then:
        if:
          condition:
              lambda: 'return id(sonic_offset) != int(x);'
          then:
            - logger.log:
                level: INFO
                format: 'Mudança no Offset Sonico : de %d para %d'
                args: ['id(sonic_offset)', 'int(x)']
            - globals.set:
                id: sonic_offset
                value: !lambda 'return int(x);'
  #------------------------------------------------------------#
  - platform: homeassistant
    id: ha_coluna_agua_total
    entity_id: input_number.coluna_agua_total_yuri
    on_value:
      then:
        if:
          condition:
              lambda: 'return id(coluna_agua_total) != int(x);'
          then:
            - logger.log:
                level: INFO
                format: 'Mudança na Coluna de Agua : de %d para %d'
                args: ['id(coluna_agua_total)', 'int(x)']
            - globals.set:
                id: coluna_agua_total
                value: !lambda 'return int(x);'
  #------------------------------------------------------------#
  - platform: homeassistant
    id: ph_aquario
    entity_id: sensor.ph_aquario_da_yuri  
  #------------------------------------------------------------#
  - platform: dallas_temp
    name: "Temperatura"
    update_interval: "${temp_time}"
    id: temperatura
    filters:
      - filter_out: nan
      - clamp:
          min_value: 0

#------------------------------------------------------------#
  - platform: ultrasonic  
    id: distancia_agua
    trigger_pin: ${dist_pin_trig}
    echo_pin: ${dist_pin_eco}
    name: "Distância da Água"
    unit_of_measurement: "cm"
    icon: "mdi:waves-arrow-up"
    accuracy_decimals: 3
    update_interval: ${nivel_time}
    timeout: 4.0m
    pulse_time: 10us
    internal: true
    filters:
       - filter_out: nan
       # HC-SR04 Returns in METERS, nothing to change.
       - lambda: return (x / 10);       #  JSN-SR04T return in Centimeters. All calculations are on METERS ! 
    on_value:
      - sensor.template.publish:
          id: nivel
          state: !lambda return ( (id(coluna_agua_total) - (id(distancia_agua).state*1000.0 - id(sonic_offset))) * 100 ) / id(coluna_agua_total);
      # x = leitura atual em m
      # Altura Total : 50 cm       AT 
      # Offset do Sensor= 2 cm     OS 
      # Coluna de Agua = 42 cm     CA
      # FALTA = (x*100 - OS) =  (x*100 - 2)  
      # SOBRANDO = (CA - FALTA) = CA - (x*100 - OS)
      # % = (SOBRANDO * 100) / CA

  - platform: template        # Nivel da Agua
    name: "Nível da Água"
    id: nivel
    unit_of_measurement: '%'
    accuracy_decimals: 0
    icon: "mdi:water-percent"
    filters:
        - filter_out: nan
        - median: 
            send_first_at: 1
            window_size: 4
            send_every: 2

 #------------------------------------------------------------#
  - platform: pulse_counter
    name: "Pulsos"
    id: fluxo_pulsos
    internal: true
    #use_pcnt: false
    #pin: ${flux_pin}
    pin:
      number: ${flux_pin}
      #inverted: true
      mode:
        input: true
        pullup: true
    update_interval: "${flux_time}s"
    icon: "mdi:wave-undercurrent"
    unit_of_measurement: "pulsos"
    accuracy_decimals: 0
    filters:
      - filter_out: nan

  - platform: template            # Fluxo / Minuto
    name: "Fluxo por Min."
    device_class: volume_flow_rate
    id: fluxo_min
    unit_of_measurement: 'L/min'
    accuracy_decimals: 1
    icon: "mdi:waves-arrow-right"
    filters:
        - filter_out: nan
    lambda: |- 
      if (id(fluxo_pulsos).state > 0) {
        return ( (id(fluxo_pulsos).state  / ${flux_time}) / id(freq_fluxo)  ); 
      } else {
        return 0;
      }

  - platform: total_daily_energy
    name: "Litros Filtrados"
    power_id: fluxo_min
    unit_of_measurement: "L"
    icon: "mdi:cup-water"
    state_class: "total_increasing"

  - platform: template            # Fluxo / Hora
    name: "Fluxo por Hora"
    #device_class: volume_flow_rate
    id: fluxo_hora
    unit_of_measurement: 'L/h'
    accuracy_decimals: 1
    icon: "mdi:waves-arrow-right"
    filters:
        - filter_out: nan
    lambda: |- 
      if (id(fluxo_pulsos).state > 0) {
        return ( (id(fluxo_pulsos).state  / ${flux_time}) / id(freq_fluxo) ) * 60;
      } else {
        return 0;
      }

#------------------------------------------------------------#
  - platform: bh1750
    name: "Iluminação"
    address: 0x23
    update_interval: ${luz_tempo}
    id: lux_aquario

#------------------------------------------------------------#   
  - platform: adc                  # PH
    pin: ${ph_pin}
    id: ph
    name: "pH ads"
    update_interval: ${ph_time}
    unit_of_measurement: V
    accuracy_decimals: 5
    attenuation: auto   # Need for ESP32 !!!!!
    # https://esphome.io/components/sensor/index.html#sensor-filters
    filters:
      #- multiply: 3.3    #needed for WEMOS D1_mini
      - median:
          window_size: 7
          send_every: 4
          send_first_at: 3
####################################################################################
